spring:
  application:
    name: cx-web
  thymeleaf:
   prefix: classpath:/template/
   suffix: .html
   mode: HTML5
   encoding: UTF-8
   content-type: text/html
   cache: false
  profiles:
    active: prod
zuul:
  routes:
    post-service:
      path: /post/**
      service-id:
        post-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/    